= Posts by categories
:page-liquid:
:page-permalink: /posts/categories

{% assign max = 0 %}
{% for category in site.categories %}
    {% if category[1].size > max %}
    {% assign max = category[1].size %}
    {% endif %}
{% endfor %}

{% for i in (1..max) reversed %}
    {% for category in site.categories %}
        {% if category[1].size == i %}
* xref:#{{ category[0] | slugify }}[*{{ category[0] }}* _{{ i }}_]
        {% endif %}
    {% endfor %}
{% endfor %}

{% for i in (1..max) reversed %}
    {% for category in site.categories %}
        {% if category[1].size == i %}
== {{ category[0] }}
            {% for post in category.last %}
=== link:{{ post.url | relative_url }}[{{ post.title | strip_html }}]
                {% if post.date %}
                {% assign date_format = site.date_format | default: "%d.%m.%Y" %}
icon:calendar[] {{ site.data.ui-text[site.locale].date | default: "Date" }}: {{ post.date | date: date_format }}{% if post.update %} - {{ post.update | date: date_format }}{% endif %}
                {% endif %}

                {% if post.categories %}
                {% assign categories = post.categories | sort_natural %}
icon:folder[] {{ site.data.ui-text[site.locale].categories | default: "Categories" }}: {% for category in categories %}xref:#{{ category | slugify }}[{{ category }}]{% unless forloop.last %}, {% endunless %}{% endfor %}
                {% endif %}

                {% if post.tags %}
                {% assign tags = post.tags | sort_natural %}
icon:tag[] {{ site.data.ui-text[site.locale].tags | default: "Tags" }}: {% for tag in tags %}xref:#{{ tag | slugify }}[{{ tag }}]{% unless forloop.last %}, {% endunless %}{% endfor %}
                {% endif %}
            {% endfor %}
[.right]
xref:#{{ page-title }}[{{ site.data.ui-text[site.locale].back_to_top | default: "Back to top" }} &uarr;]
        {% endif %}
    {% endfor %}
{% endfor %}
