= Posts by dates
:icons: font
:showtitle:
:page-liquid:
:page-permalink: /posts/dates

{% assign years = site.posts | where_exp: "item", "item.hidden != true" | group_by_exp: "post", 'post.date | date: "%Y"' %}
{% for year in years %}
* xref:#{{ year.name }}[*{{ year.name }}* {{ year.items | size }}]
{% endfor %}

{% for year in years %}
== {{ year.name }}
    {% for post in year.items %}
=== link:{{ post.url | relative_url }}[{{ post.title | strip_html }}]
        {% if post.date %}
        {% assign date = post.date %}
        {% assign date_format = site.date_format | default: "%d-%m-%Y" %}
icon:calendar[] {{ site.data.ui-text[site.locale].date | default: "Date" }}: {{ date | date: date_format }}
        {% endif %}

        {% if post.categories %}
icon:folder[] {{ site.data.ui-text[site.locale].categories | default: "Categories" }}: {{ post.categories | join: ", " }}
        {% endif %}

        {% if post.tags %}
        {% assign tags = post.tags | sort_natural %}
icon:tag[] {{ site.data.ui-text[site.locale].tags | default: "Tags" }}: {% for tag in tags %}xref:#{{ tag }}[{{ tag }}]{% unless forloop.last %}, {% endunless %}{% endfor %}
        {% endif %}
    {% endfor %}
xref:#{{ page-title }}[{{ site.data.ui-text[site.locale].back_to_top | default: "Back to top" }} &uarr;]
{% endfor %}