= Posts by tags
:page-liquid:
:page-permalink: /posts/tags

{% assign max = 0 %}
{% for tag in site.tags %}
    {% if tag[1].size > max %}
    {% assign max = tag[1].size %}
    {% endif %}
{% endfor %}

{% for i in (1..max) reversed %}
    {% for tag in site.tags %}
        {% if tag[1].size == i %}
* xref:#{{ tag[0] | slugify }}[*{{ tag[0] }}* _{{ i }}_]
        {% endif %}
    {% endfor %}
{% endfor %}

{% for i in (1..max) reversed %}
    {% for tag in site.tags %}
        {% if tag[1].size == i %}
== {{ tag[0] }}
            {% for post in tag.last %}
=== link:{{ post.url | relative_url }}[{{ post.title | strip_html }}]
                {% if post.date %}
                {% assign date_format = site.date_format | default: "%d.%m.%Y" %}
icon:calendar[] {{ site.data.ui-text[site.locale].date | default: "Dates" }}: {{ post.date | date: date_format }}{% if post.update %}{% for update in post.update %}, {{ update | date: date_format }}{% endfor %}{% endif %}
                {% endif %}

                {% if post.categories %}
icon:folder[] {{ site.data.ui-text[site.locale].categories | default: "Categories" }}: {{ post.categories | join: ", " }}
                {% endif %}

                {% if post.tags %}
                {% assign tags = post.tags | sort_natural %}
icon:tag[] {{ site.data.ui-text[site.locale].tags | default: "Tags" }}: {% for tag in tags %}xref:#{{ tag | slugify }}[{{ tag }}]{% unless forloop.last %}, {% endunless %}{% endfor %}
                {% endif %}
            {% endfor %}
[.right]
xref:#{{ page-title }}[{{ site.data.ui-text[site.locale].back_to_top | default: "Back to top" }} &uarr;]
        {% endif %}
    {% endfor %}
{% endfor %}