# Site settings
keywords: academic, it, science
lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: ⚛️  # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: https://kgv.github.io # the base hostname & protocol for your site
last_updated: false # set to true if you want to display last updated in the footer
impressum_path:  # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR

# Author settings
author:
  first_name: Giorgi
  middle_name: Valadimirovich
  last_name: Kazakov
  laboratory: Laboratory of Lipid Metabolism, Timiryazev Institute of Plant Physiology, Russian Academy of Sciences
  institute: Timiryazev Institute of Plant Physiology, Russian Academy of Sciences
  academy: Russian Academy of Sciences
  location: Russia, Moscow
  email: kazakov.giorgi.valadimirovich@gmail.com
  github: kgv

# posts
permalink: /posts/:year/:month/:day/:title

collections:
  devices:
    output: true
    permalink: /:collection/:title/
  projects:
    output: true
    permalink: /:collection/:title/
  publications:
    output: true
    permalink: /:collection/:title/

defaults:
  # posts
  - scope:
      path: ""
      type: posts
    values:
      layout: page
  # collections/devices
  - scope:
      path: ""
      type: devices
    values:
      layout: page
  # collections/projects
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  # collections/publications
  - scope:
      path: ""
      type: publications
    values:
      layout: publication
  # pages
  - scope:
      path: "_pages"
    values:
      layout: page

include:
- _pages
- _pages/posts
exclude:
- LICENSE
- README.adoc
- Gemfile
- Gemfile.lock
- Rakefile

asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    showtitle: true
    icons: font
    idseparator: _
    nofooter:
    stem: latexmath
    figure-caption: Изображение
    figures-caption: Изображения
    table-caption: Таблица
    details: Детали
    where: Где
    stylesdir: css
    source-highlighter: coderay
