= Readme
:experimental:
ifndef::env-github[:toc:]

{page-title}

== Regex

.Regex
[cols="2*"]
|===
|\$([^$]*)\$|stem:[$1]
|(stem:\[.*)\\mu L(.*\])
|===

== Open Babel

obabel -i smi ~/input.smi -o xyz -O ~/out --gen3d --energy=mmff94 -d
obabel -i smi ~/input.smi -o report -O ~/out.report -d --energy=mmff94 --gen3d --canonical --conformer --nconf 50 --score energy

obabel -:"CCCCCCCCC/C=C\C/C=C\CCCC(=O)O" -i smi -o svg -O ~/git/kgv/kgv.github.io/assets/posts/2024-05-22/out.svg -d --minimize=mmff94 --energy=mmff94 --gen3d --canonical --conformer --nconf 255 --weighted

obabel -:"CCCCCCCCC/C=C\C/C=C\CCCC(=O)O" -i smi -o report -O ~/git/kgv/kgv.github.io/assets/posts/2024-05-22/out.report -d --minimize=mmff94 --energy=mmff94 --gen3d --canonical --conformer --nconf 255 --weighted

obabel -i smi ~/git/kgv/kgv.github.io/assets/posts/input/input.smi -o report -O ~/git/kgv/kgv.github.io/assets/posts/2024-05-22/out.report -d --minimize=mmff94 --energy=mmff94 --gen3d --canonical --conformer --nconf 255 --weighted

obabel -i smi ~/input.smi -o report -O ~/git/kgv/kgv.github.io/assets/posts/2024-05-22/0out.report -d --gen3d --canonical --conformer --systematic

obabel -i smi ~/input.smi -o report -O ~/git/kgv/kgv.github.io/assets/posts/2024-05-22/0out.report -d --gen3d --canonical --conformer --nconf 255 --weighted

obabel -i smi ~/git/kgv/kgv.github.io/assets/posts/input/input.smi -o report -O ~/git/kgv/kgv.github.io/assets/posts/output/out.report -d -m --gen3d best --canonical --minimize=mmff94 --energy=mmff94

obabel -i smi ~/git/kgv/kgv.github.io/assets/posts/input/input.smi -o report -O ~/git/kgv/kgv.github.io/assets/posts/2024-05-22/0out.report -d --minimize=mmff94 --energy=mmff94 --gen3d --canonical --conformer --nconf 255 --weighted

-d:: Delete all hydrogens
--energy <options>:: Forcefield energy evaluation.
--minimize <options>:: Forcefield energy minimization.

The command line option --conformer allows performing conformer searches using a range of different algorithms and options:

--nconf #:: number of conformers to generate

Forcefield-based methods for finding stable conformers:

--systematic:: systematically (exhaustively) generate all conformers
--random:: randomly generate conformers
--weighted:: weighted rotor search for lowest energy conformer
--ff <name>:: select a forcefield (default = MMFF94)

Genetic algorithm based methods (default):

--children #:: number of children to generate for each parent (default = 5)
--mutability #:: mutation frequency (default = 5)
--converge #:: number of identical generations before convergence is reached
--score #:: scoring function [rmsd|energy] (default = rmsd (root mean square deviation))

obabel -i smi ~/in.smi -o report -O ~/git/kgv/kgv.github.io/assets/posts/2024-05-22/2꞉18-Δ9,13ω5,9/out.report -d -m --minimize=mmff94 --energy=mmff94 --gen3d --canonical --conformer --nconf 255 --weighted

`(?:\n{2})(.+)` +
`^\W*[A-Za-z]\W*\d+\W*\d+\.\d+ ` +

./assets/posts/2024-05-22/temp

https://hjkgrp.mit.edu/tutorials/2013-10-29-geometries-strings-smiles-and-openbabel[conformer]


> [!NOTE]
> Заметки по эксперименту.

> [!TIP]
> Helpful advice for doing things better or more easily.

> [!IMPORTANT]
> ВАЖНО, если не сделать, то при.

> [!WARNING]
> ПРЕДУПРЕЖДЕНИЕ, если не сделать, то могут быть необратимые последствия для текущего эксперимента, образца.

> [!CAUTION]
> ВНИМАНИЕ, если не сделать, то могут быть необратимые последствия для человека, оборудования.
