= Разделение энантиомеров триацилглицеринов, состоящих из трех различных жирных ацилов, и их поведение при элюировании в хиральной хроматографии
:page-categories: [Experiment]
:page-update: [2024-05-23, 2024-05-24]
:stem: latexmath

https://pubs.acs.org/doi/10.1021/acs.analchem.4c02513


Науки о продуктах питания, факультет технологий, Университет Турку, Турку, FI-20014, Финляндия

Аннотация: Хроматографическое разделение энантиомеров триацилглицеринов (ТАГ) — очень сложная задача аналитической химии из-за сходных физико-химических свойств. Анализ хиральных ТАГ имеет решающее значение для углубления знаний в области биохимии липидов и понимания питательных свойств жиров и масел. Таким образом, цель данного исследования состояла в систематическом изучении хирального разделения ТАГ, состоящих из трех различных жирных ацилов (ЖК). С помощью рециркулирующей хиральной ВЭЖХ-системы было проанализировано 33 асимметричных энантиомерных пары ТАГ, включая 49 синтезированных энантиомерно чистых ТАГ и рацемических ТАГ. Двадцать шесть энантиомерных пар были успешно разделены. В целом, наличие как ненасыщенных, так и насыщенных ЖК во внешних положениях или разницы в длине углеродной цепи между двумя насыщенными ЖК во внешних положениях способствовало разделению энантиомеров. Время удерживания при разделении отрицательно коррелировало с количеством атомов углерода sn-3 у раннего элюирующего энантиомера и положительно коррелировало с разницей в количестве атомов углерода между sn-1 и sn-3. Когда образцы изучали в отдельных группах на основании ненасыщенности и региоизомеров, количество атомов углерода ацила и степень ненасыщенности ЖК во всех трех положениях влияли на разделение и поведение при элюировании хиральных ТАГ, что указывает на активную роль как межмолекулярных взаимодействий, так и стерических препятствий. Это первое систематическое исследование хирального разделения ТАГ, состоящих из трех различных ЖК, с использованием большого количества энантиомерных пар. Новые результаты, касающиеся поведения энантиомеров ТАГ в хиральной среде, предоставляют важное руководство и ориентир для стереоспецифического изучения химии и биохимии природных липидов.

Введение:

Хроматографическое разделение региоизомеров и энантиомеров триацилглицеринов (ТАГ) долгое время оставалось сложной задачей, несмотря на растущий интерес к хиральному хроматографическому анализу ТАГ [1-3]. Еще в 1958 году Мэттсон и Латтон [4] утверждали, что природное распределение жирных ацилов (ЖК) в глицериновой основе не является случайным, что является общепризнанным фактом. Молекула ТАГ становится хиральной, если различные ЖК этерифицированы во внешних положениях (sn-1 и sn-3) глицерина. Таким образом, ТАГ, состоящие из трех различных ЖК (ТАГ ABC), являются хиральными. Энантиомеры различаются по своей трехмерной конфигурации в стереогенном центре sn-2 и, следовательно, обычно проявляют различное биохимическое поведение и физиологические свойства, несмотря на идентичный химический состав. Например, поведение смеси энантиомеров ТАГ при плавлении отличается от поведения чистых энантиомеров, а поведение асимметричных ТАГ при кристаллизации влияет на физические свойства продуктов на основе жира [10].

Хотя большинство распространенных ТАГ в пищевых маслах и жирах состоят из одного (например, O_O_O, L_L_L) или двух видов ЖК (например, O_O_P, O_P_P, P_L_L, P_L_P и O_O_S), ТАГ ABC также часто представляют собой характерные соединения некоторых масел [11], включая P_Po_L, Po_L_S, P_Po_O и P_O_A в оливковом масле [12, 13] или P_O_M в пальмовом масле [14, 15]. В некоторых маслах содержание ТАГ ABC примечательно высоко, например, свиное сало содержит P_O_S, P_L_O и P_L_S в качестве основных видов ТАГ, при этом на долю ТАГ ABC приходится более 37 % от общего количества ТАГ [16]. Другими интересными примерами являются грудное молоко человека, содержащее до 20 % O_P_L и до 50 % ТАГ ABC [17, 18], и масло какао, содержащее 38 % P_O_S [19].

ТАГ ABC могут образовывать шесть изомеров, которые чрезвычайно сложно разделить одновременно хроматографическим способом. Для идентификации и разделения ТАГ изучено несколько хроматографических методов. Нагай и др. [3] оценили изомерное разделение ТАГ ABC P_O_S, P_O_L и S_O_L с использованием колонки CHIRALPAK IF-3 и ацетонитрила в качестве подвижной фазы. Хотя изомеры не были полностью разделены, им удалось дифференцировать шесть изомеров S_O_L и P_S_O и предсказать порядок их элюирования по региоизомерам в соответствии с соотношением фрагментных ионов диацилглицерина, проанализированных с помощью системы ESI-MS/MS. Лиса и Холчапек [20] проанализировали несколько ТАГ ABC, включая P_O_L, Ln_O_A, O_L_S, S_Ln_O, S_Ln_L и L_O_Ln, с использованием двух хиральных колонок Lux Cellulose-1 и гексана и гексан-2-пропанола в качестве подвижных фаз. Все другие энантиомеры были хотя бы частично разделены, за исключением Ln_O(sn-2)_A и P_O(sn-2)_L, которые содержали как насыщенные ЖК (НЖК), так и ди- или триненасыщенные (Н) ЖК во внешних положениях. Изменяя степень модификации серебром стационарной фазы катионообменной колонки, Санторо и др. [21] добились лучшего контроля механизма удерживания. Их метод имел преимущество в виде более короткого времени анализа, в течение которого можно было разделить региоизомерные пары P_O(sn-2)_S и P_S(sn-2)_O. С помощью 2D ВЭЖХ-системы, состоящей из обращенно-фазовой ВЭЖХ в неводной среде и ВЭЖХ с ионами серебра, Чжао и др. [22, 23] смогли разделить некоторые региоизомеры P_L(sn-2)_Ln, L_O(sn-2)_Ln и S_L(sn-2)_O.

Хотя хиральная хроматография применялась для разделения энантиомеров ТАГ, данные о правиле элюирования ТАГ ABC в настоящее время неубедительны. Отсутствуют знания о поведении ТАГ с различными изомерными структурами при элюировании в хиральной системе. Такие знания имеют решающее значение для понимания механизмов удерживания, элюирования и разделения позиционных изомеров ТАГ. Следовательно, цель данного исследования состояла в проведении систематического исследования элюирования и разделения ТАГ ABC, содержащих различные типы жирных ацилов, и в изучении влияния структурных характеристик и позиционного распределения жирных ацилов на разделение изомеров ТАГ на хиральных колонках. Большой проблемой при стереоспецифическом анализе ТАГ является отсутствие коммерческих стандартов энантиомерно чистых эталонных соединений [24, 25]. Для облегчения исследования было синтезировано 49 энантиомерно чистых ТАГ ABC (таблица S1); они вместе с 16 коммерческими региочистыми рацемическими ТАГ (таблица S2) образовали 33 энантиомерные пары (ECN 32-52). Энантиомеры были проанализированы с помощью хиральной ВЭЖХ с рециркулирующей системой и УФ-детектором. В данном исследовании систематически изучалось разделение энантиомерных пар ТАГ и изучалась связь между структурой и поведением при элюировании. Насколько известно авторам, это первое исследование, в котором сообщается о систематическом анализе такого большого количества энантиомеров ТАГ ABC. Результаты данного исследования дают новое представление о хроматографическом поведении хиральных ТАГ при элюировании, улучшая современное понимание механизма удерживания изомеров ТАГ на хиральных стационарных фазах и продвинутый регио- и стереоспецифический анализ сложных природных липидов.

Экспериментальный раздел:

Номенклатура и сокращения. Для описания структуры ТАГ использовалась стереоспецифическая нумерация (sn) для различения положения ЖК на глицериновой основе в соответствии с руководством LIPID MAPS [26]. ТАГ называются A_B_C, если известен только состав ЖК, независимо от позиционного распределения ЖК. Если известен только ЖК в среднем положении, например, B, применяется терминология, которая различает возможные конфигурации. Более конкретно, смесь ТАГ, которая содержит оба энантиомера в молярном соотношении 1:1, называется rac-A_B(sn-2)_C или в противном случае ТАГ A_B(sn-2)_C относится к нерацемическим смесям. A/B/C обозначает ТАГ с ЖК A, B и C, этерифицированными в положениях sn-1, 2 и 3 соответственно. Эквивалентное число атомов углерода (ECN) определяется как количество атомов углерода в остатках ЖК минус удвоенное количество двойных связей [27]. НЖК обозначает насыщенную жирную кислоту; НЖК — ненасыщенную жирную кислоту; ECN — эквивалентное число атомов углерода; C — количество атомов углерода ацила; AC — разницу в количестве атомов углерода ацила между различными положениями; а DB — двойную связь. Сокращения для отдельных ЖК обозначаются как Bu = 4:0 (масляная кислота), C = 10:0 (каприновая кислота), La = 12:0 (лауриновая кислота), M = 14:0 (миристиновая кислота), P = 16:0 (пальмитиновая кислота), S = 18:0 (стеариновая кислота), O = 18:1 (олеиновая кислота), L = 18:2 (линолевая кислота), Ln = 18:3(n-6) (гамма-линоленовая кислота), A = 20:0 (арахидоновая кислота), E = 20:5 (эйкозапентаеновая кислота) и D = 22:6 (докозагексаеновая кислота).

Химикаты и эталонные соединения триацилглицеринов. Метанол и гексан были приобретены у Sigma-Aldrich Corporation (Сент-Луис, штат Миссури), а 2-пропанол — у VWR International (Рэднор, штат Пенсильвания). Все растворители были класса ВЭЖХ.

Сорок девять энантиомеров ТАГ ABC (ECN 32-52, таблица S1) были синтезированы в Исландском университете. Эти соединения можно разделить на четыре категории в зависимости от характера насыщения или ненасыщения входящих в их состав ЖК: во-первых, те, которые содержат два различных НЖК, один из которых этерифицирован в конечном положении sn-1/3 (S), а другой — в положении sn-2 (S'), и один НЖК, расположенный в оставшемся конечном положении sn-1/3, категория USS'-типа, и во-вторых, ТАГ, содержащие НЖК в положении sn-2 и два НЖК в двух положениях sn-1/3, категория SUS'-типа. Аналогичным образом, третья и четвертая группы — это UU'S- и USU'-типа, содержащие два различных НЖК и один НЖК.

Синтез ТАГ, относящихся к первой группе, был осуществлен шестистадийным хемоферментативным путем, описанным Гудмундссоном и др., начиная с энантиомерно чистого солькеталя (1,2-изопропилиден-sn-глицерина) с (S)- или (R)-солькеталем в качестве хирального предшественника [28]. Метод основан на использовании бензильной эфирной защитной группы, высокорегиоселективной иммобилизованной липазы Candida antarctica (CAL-B) и, наконец, связывающего агента EDCI (1-этил-3-(3-(диметиламино)пропил)карбодиимида). Некоторые из ТАГ SUS'-типа были синтезированы аналогичным хемоферментативным методом, также описанным Гудмундссоном и др. [28] и Кристинссоном и Харальдссоном [29], на этот раз с двумя стадиями липазы Candida antarctica. Синтетическая стратегия была основана на легком удалении бензильной защитной группы путем каталитического гидрогенолиза, который не затрагивает НЖК. Иначе обстояло дело в присутствии НЖК, поскольку они склонны к гидрированию в условиях депротекции. Оставшиеся ТАГ SUS'-типа и ТАГ, относящиеся к дважды ненасыщенным категориям UU'S и USU' ТАГ, были получены аналогичным шестистадийным хемоферментативным методом, который был модифицирован для учета повышенного количества НЖК и наличия НЖК во время депротекции. Это потребовало перехода на другую р-метоксибензильную защитную группу, которая подвергается расщеплению в мягких окислительных условиях с использованием DDQ (2,3-дихлор-5,6-дициано-1,4-бензохинона), в которых, как наблюдалось, мононенасыщенные ЖК легко выживают. Все промежуточные и конечные продукты ТАГ были получены с высокой химической и энантиомерной чистотой. Для полной характеристики молекулярных структур использовались ЯМР-спектроскопия H и 13C, ИК-спектроскопия и удовлетворительный анализ масс-спектрометрии с высоким разрешением и точностью, а измерение удельного вращения и хиральная рециркулирующая ВЭЖХ использовались для определения энантиомерной чистоты ТАГ.

Шестнадцать коммерческих рацемических образцов ТАГ (ECN 42-52, таблица S2) были приобретены у Larodan (Сольна, Швеция), содержали структуры SUS'-, SS'U-, UU'S- и USU'-типа и имели чистоту не менее 98 %. Среди всех образцов энантиомерные пары были смешаны в неравных соотношениях, или рацемическая смесь была обогащена одним энантиомером для определения порядка элюирования. Все образцы разбавляли изопропанолом/гексаном 4:1 до конечной концентрации 1 мг/мл, а объем инъекции составлял 15 мкл. В некоторых случаях, когда отклика от УФ-детектора было недостаточно, концентрация увеличивалась до 2 мг/мл. Четыре образца, каждый из которых содержал триплеты региоизомеров, были приготовлены путем смешивания синтезированных энантиомерно чистых ТАГ (таблица 1) для проверки применимости того же метода для разделения региоизомеров.

Хроматографические условия. Рацемические образцы ТАГ и смешанные образцы ТАГ анализировали методом, ранее опубликованным нашей группой [31], с использованием двух хиральных колонок (CHIRALCEL OD-RH, 150 × 4,6 мм, 5 мкм, Chiral Technologies Europe, Илькирш, Франция), метанола в качестве подвижной фазы и системы рециркуляции образцов. Использовались как автоматическое переключение клапанов (с помощью программы LCsolution, Shimadzu Corporation, Киото, Япония), так и ручное переключение. Для численного определения разделения рассчитывалось соотношение пик-долина (p/v) для каждой энантиомерной пары. Когда соотношение p/v было больше 1, пики считались разделенными, а время удерживания (tr) первого элюирующего энантиомера представлено как tr при разделении. Коэффициенты разделения (a) рассчитывались в конце хроматографического анализа. Для оценки эффективности системы теоретические числа тарелок (N) рассчитывались с использованием времени удерживания и ширины пика чистых соединений первого элюирующего энантиомера каждой энантиомерной пары после первого прохода через колонки без рециркуляции. Все хроматографические параметры рассчитывались с помощью программного обеспечения LCsolution.

Статистический анализ. Корреляционный анализ Пирсона был проведен для изучения корреляции между длиной углеродной цепи, количеством двойных связей, разницей в количестве атомов углерода между длинами цепей в различных положениях, tr, ECN и tr при разделении с помощью программного обеспечения IBM SPSS Statistics 25.0 (IBM, Армонк, штат Нью-Йорк, США) с двусторонней значимостью. Значимость данного исследования была установлена на уровнях 0,05 и 0,01. Все данные были проверены на нормальное распределение.

Результаты и обсуждение:

Разделение энантиомеров. В данном исследовании было проанализировано 33 энантиомерные пары, и все хроматограммы приведены на рисунке S1. Семь пар из них не были разделены в течение времени хроматографического анализа < 8 ч в применяемых условиях. Время анализа не могло быть продлено, поскольку уширение пиков ограничивает количество циклов. Двадцать шесть энантиомерных пар были четко разделены (рисунок 1). В качестве примера базового разделения на рисунке 3A представлена хроматограмма энантиомеров O/La/P. После четырех проходов через колонки наблюдалось видимое плечо, а два энантиомера были разделены по базовой линии после 15 проходов через колонки.

В одинаковых условиях структурные факторы, такие как длина углеродной цепи ацила, количество двойных связей и число ECN, влияют на эффективность разделения ТАГ. В таблице 2 приведены результаты корреляционного анализа Пирсона разделенных энантиомерных пар. Как известно также из обращенно-фазовой хроматографии, время удерживания и число ECN имеют значительную положительную корреляцию. Это согласуется с предыдущими результатами [31]. Исключение составляют только ТАГ с очень длинными цепями и сильно ненасыщенными (DB > 6) ЖК [32]. Время удерживания влияет на хроматографическое поведение и разделение. Например, если образец находится в стационарной фазе слишком короткое время, он может не разделиться, как показано в случае S_E(sn-2)_Bu (рисунок S2A-AG). В соответствии с той же логикой, время удерживания при разделении отрицательно коррелирует со временем удерживания при однократном проходе через колонку и числом ECN (рисунок 2A). Другими словами, чем больше число ECN и чем больше время удерживания, тем меньше времени требуется для разделения энантиомеров. В данном наборе данных время удерживания при разделении отрицательно коррелировало с количеством атомов углерода sn-3 (рисунок 2B) и положительно коррелировало с разницей в количестве атомов углерода ацила между ЖК sn-1 и sn-3 (рисунок 2C).

Основываясь на результатах корреляции, мы обнаружили, что степень ненасыщенности ЖК в образце влияет на поведение при элюировании. Следовательно, разделение энантиомеров изучалось в соответствии с описанной ранее группировкой. Во-первых, ТАГ с одним НЖК и двумя НЖК относятся к категории ТАГ USS'-типа. Затем ТАГ, которые содержат либо два НЖК, либо два НЖК во внешних положениях, относятся к категориям SUS'- или USU'-типа ТАГ, и, наконец, ТАГ с двумя НЖК и одним НЖК относятся к категории UU'S-типа ТАГ.

ТАГ USS'-типа. В общей сложности 14 из 15 энантиомерных пар ТАГ USS'-типа были разделены (таблица 3, рисунок 1A). Это была самая большая группа в данном исследовании. Как видно из таблицы 3, ЖК в положении sn-1 первого элюирующего энантиомера во всех случаях был ненасыщенным, что указывает на то, что ТАГ с НЖК в положении sn-1 всегда элюируются раньше соответствующих энантиомеров. Это наблюдение подтвердило наши предыдущие результаты, касающиеся порядка элюирования энантиомеров ТАГ USS'- и UU'S-типа [31, 32].

Вместо разрешения соотношение p/v было применимо для всех энантиомерных пар, а также в случаях слабого разделения. Другим хроматографическим параметром для мониторинга разделения был коэффициент разделения (a), который выражает относительное удерживание энантиомеров, но не учитывает ширину пиков. Теоретические числа тарелок (N) рассчитывались для оценки общей эффективности системы с использованием времени удерживания и ширины пика чистого соединения первого элюирующего энантиомера каждой энантиомерной пары после первого прохода через колонку. В случае энантиомерных пар поведение энантиомеров при удерживании влияет на ширину пика. N — не самый оптимальный параметр для отслеживания эффективности системы рециркулирующей ВЭЖХ, поскольку «длина колонки» меняется в зависимости от количества циклов.

В отличие от результатов Лисы и Холчапека [20], мы обнаружили, что ЖК в положении sn-2 также оказывает значительное влияние на эффективность хирального разделения энантиомеров ТАГ. На рисунке 1D сравнивается время, необходимое для разделения энантиомеров между двумя уникальными наборами структурированных ТАГ, каждый из которых состоит из пяти пар энантиомерно чистых ТАГ. Во всех этих парах O и P были ЖК либо в положениях sn-1/3 и sn-2 (серия O_P(sn-2)_S, O_P(sn-2)_M, O_P(sn-2)_A, O_P(sn-2)_La и O_P(sn-2)_C) (рисунок S1F,Q,C,J,U), либо в положениях sn-1 и sn-3 (серия O_S(sn-2)_P, O_M(sn-2)_P, O_La(sn-2)_P и O_C(sn-2)_P) (рисунок S1G,P,H,D,V). Как показано на рисунке 1D, ЖК в среднем положении оказывает явное влияние на разделение энантиомерных пар: чем меньше разница в длине углеродной цепи ацила между sn-2 и sn-3 положениями первого элюирующего энантиомера, тем быстрее разделение энантиомеров. Когда разница в длине углеродной цепи между ЖК sn-2 и sn-3 достигает 6, как в случае O_P(sn-2)_C, энантиомеры не разделяются. Когда разница в количестве атомов углерода была одинаковой, энантиомеры, у которых длина углеродной цепи в положении sn-3 была больше, чем в положении sn-2, разделялись быстрее (таблица 3). Кроме того, время разделения энантиомеров O_P(sn-2)_S, O_P(sn-2)_M, O_P(sn-2)_A, O_P(sn-2)_La и O_P(sn-2)_C увеличилось по сравнению с их региоизомерами. Таким образом, влияние ЖК sn-2 на эффективность разделения может быть даже больше, чем влияние первичных положений, по крайней мере, в исследуемых хроматографических условиях. Кроме того, количество атомов углерода НЖК явно влияет на эффективность разделения, но это число не коррелирует линейно со временем, необходимым для разделения. Однако эффективность разделения была аналогичной в обоих наборах структурированных ТАГ; также O_A(sn-2)_P (tr мин при разделении 82,1 мин, соотношение p/v 1,24) практически энантиоразделяется раньше, чем O_La(sn-2)_P (tr при разделении 80,1 мин, соотношение p/v 1,02) (рисунок S1D,H).

Поскольку время, необходимое для разделения, не коррелировало положительно с количеством атомов углерода НЖК, можно сделать вывод, что в энантиоразделении ТАГ USS'-типа участвуют как притягивающие, так и отталкивающие молекулярные взаимодействия [33].

ТАГ SUS'- и USU'-типа. Большинство (7/10) ТАГ SUS'-типа разделялись (таблица 4). Для разделяемых пар SUS', за исключением тех, которые содержали длинноцепочечные n-3 ПНЖК, длина углеродной цепи двух НЖК влияла на порядок элюирования. Энантиомер с более короткой цепью ЖК в положении sn-1 всегда элюируется первым. Когда ТАГ содержат ПНЖК с пятью или более двойными связями, их поведение при элюировании больше не соответствует значениям ECN [25, 32]. Это также может объяснить поведение энантиомерной пары S_E(sn-2)_Bu, которая не разделилась, несмотря на большую разницу в количестве атомов углерода ацила между положениями sn-1 и sn-3. Большая разница в количестве атомов углерода между ЖК sn-1 и sn-3 способствовала разделению энантиомеров, что очевидно, например, при сравнении времени разделения C_O(sn-2)_P с P_O(sn-2)_A, а также La_O(sn-2)_M с La_O(sn-2)_P. P_O(sn-2)_S и M_O(sn-2)_P не были энантиоразделены в исследуемых условиях, вероятно, из-за небольшой разницы в длине углеродной цепи между ЖК sn-1 и sn-3. Увеличение количества двойных связей в среднем положении, по-видимому, увеличивает время, необходимое для разделения энантиомеров, как видно из сравнения La_O(sn-2)_P и La_L(sn-2)_P.

Ожидалось, что энантиомеры с НЖК как в положении sn-1, так и в положении sn-3 будут трудно разделить из-за высокосимметричной структуры. Действительно, хотя для их аналогов UU'S-типа было достигнуто разделение энантиомеров (La_O(sn-2)_L и P_O(sn-2)_L), по крайней мере три энантиомерные пары ТАГ USU'-типа (O_La(sn-2)_L, O_M(sn-2)_L и L_P(sn-2)_O) не разделялись в применяемых хроматографических условиях (таблица 5).

ТАГ UU'S-типа. Результаты анализа энантиомерных пар UU'S-типа приведены в таблице 5. Объединяя результаты для ТАГ USS'- и UU'S-типа, все 19 ТАГ, содержащих как НЖК (C18:1 или C18:2), так и НЖК (C12:0-C20:0) в положениях sn-1 и sn-3, были успешно разделены независимо от типа ЖК в положении sn-2 (Н или Н). Единственным исключением была энантиомерная пара O-P(sn-2)-C.

Сравнивая время разделения энантиомерных пар L_O(sn-2)_S, L_O(sn-2)_P и L_O(sn-2)_La, результаты показали, что чем длиннее углеродная цепь НЖК, тем быстрее разделяются энантиомеры. Энантиомеры O_L(sn-2)_P и O_L(sn-2)_La также следовали этому правилу. В пределах одного и того же ECN, чем больше двойных связей в положении sn-1/3, тем быстрее энантиоразделение, как замечено для L_O(sn-2)_P и O_L(sn-2)_P, а также L_O(sn-2)_La и O_L(sn-2)_La. В соответствии с правилом для ТАГ USS'-типа энантиомер с НЖК, расположенным в положении sn-1, всегда элюируется первым [31]. Полученные результаты отличались от результатов Лисы и Холчапека [20]. В их исследовании rac-P_O(sn-2)_L не разделялся, а rac-O_P(sn-2)_L и rac-P_L(sn-2)_O разделялись. Они пришли к выводу, что ТАГ с насыщенными и ди- или триненасыщенными ЖК, расположенными в положениях sn-1/3, не разделяются на хиральных колонках (Lux Cellulose-1) с использованием гексана и гексан-2-пропанола в качестве подвижной фазы. Другой пример ТАГ этого типа в нашем исследовании, L_O(sn-2)_La, также энантиоразделялся. Результаты Лисы и Холчапека согласовывались с результатами исследований Резанки и Зиглера [34] и Чена и др. [35]. Согласно Чену и др., rac-O_P(sn-2)_L и rac-P_L(sn-2)_O разделялись на хиральной колонке, заполненной трис-3,5-диметилфенилкарбаматом целлюлозы. Они в основном использовали гексан в качестве подвижной фазы. С другой стороны, rac-P_O(sn-2)_L не разделялся этим методом. Нагай и др. [3] попытались разделить энантиомеры ТАГ и позиционные изомеры P_O_L и P_S_O одновременно на колонке CHIRALPAK IF-3 (трис-3-хлор-4-метилфенилкарбамат амилозы) с использованием ацетонитрила в качестве подвижной фазы. Им удалось частично разделить P_S_O на несколько пиков, но изомеры P_O_L не были достаточно разрешены. Вместе эти результаты указывают на то, что использование различных стационарных и подвижных фаз оказывает существенное влияние на то, можно ли разделить определенные изомеры ТАГ.

Разделение региоизомерных смесей ТАГ. Для дальнейшего применения рециркулирующей ВЭЖХ 4 региоизомерных смешанных образца ТАГ (таблица 1) были проанализированы тем же методом. Хроматограммы четырех смесей ТАГ и отдельных энантиомеров приведены на рисунке S2. После более чем 20 проходов через колонки (общее время анализа более 400 мин) все пики показали некоторую асимметрию. Используя эту хиральную колонку в сочетании с методом рециркуляции, смешанные ТАГ теоретически можно разделить, если количество циклов достаточно велико. Но на практике уширение пиков и длительное время анализа ограничивают работу. Для идентификации разделенных пиков отдельный энантиомер ТАГ анализировали в тех же условиях. Смесь 1 было трудно разделить, и только небольшая асимметрия была обнаружена через 400 мин. Смесь 2 показала асимметрию через 200 мин, а два плеча можно было различить через 350 мин. Основываясь на времени удерживания отдельных энантиомеров ТАГ, первое плечо представляет собой P/O/M, а второе плечо — P/M/O. Смесь 3 была разделена на два пика разной ширины, а второй пик имел плечо, которое имело тенденцию к разделению на третий. Основываясь на времени удерживания отдельных энантиомеров ТАГ, первый пик представляет собой C/P/O, а второй пик — смесь P/C/O и P/O/C. Поскольку плечо второго пика находилось справа, это мог быть P/C/O. Смесь 4 (рисунок 3B) была разделена на два пика через 400 мин. Основываясь на времени удерживания отдельных энантиомеров ТАГ, первый пик представляет собой P/L/La. Второй — смесь La/P/L и P/La/L. Это согласовалось с предыдущим исследованием [36], в котором ТАГ с двумя НЖК, расположенными в положении sn-1,2 или sn-2,3, как ожидается, имеют более длительное время удерживания, поскольку взаимодействие стационарной фазы с двойными связями, даже стационарная фаза и комбинация растворителей не совпадали с текущим исследованием.

В целом, региоизомеры имеют тенденцию к очень похожему поведению при элюировании, и их трудно разделить с помощью изученной комбинации колонки и растворителя. Таким образом, в анализе региоизомеров ТАГ предпочтительнее масс-спектрометрическое детектирование [37, 3

Выводы:

Это первое систематическое исследование энантиомерного разделения и поведения при элюировании большого числа ТАГ ABC с использованием рециркуляционной хиральной хроматографии. Было изучено тридцать три энантиомерные пары, включая 49 асимметрично синтезированных энантиомерно чистых ТАГ и 16 региочистых рацемических ТАГ. Двадцать шесть из 33 энантиомерных пар были разделены, а хиральное хроматографическое разделение и поведение при элюировании были систематически изучены.

В дополнение к основной корреляции между числом ECN ТАГ и скорректированным временем удерживания были выявлены новые корреляции. Tr при разделении коррелирует не только с количеством атомов углерода sn-3, но и с разницей в количестве атомов углерода между первичными ЖК, что указывает на то, что длина ЖК в первичном положении значима в процессе разделения. Хотя ЖК в положении sn-2 не показал значительной корреляции с tr при разделении при изучении всех данных, он продемонстрировал очевидное влияние на разделение ТАГ USS'-типа. В целом было ясно, что и длина углеродных цепей ацила, и степень ненасыщенности во всех трех положениях участвуют в хиральном разделении. Наши результаты позволяют предположить, что в процессе разделения играют роль как межмолекулярные взаимодействия, так и стерические препятствия.

Этот метод оказался неэффективным для разделения региоизомеров, где МС широко используется в качестве эффективного метода благодаря получаемой структурной информации [39]. Для энантиомерного анализа ТАГ хиральное хроматографическое разделение неизбежно. Новые знания, полученные в данном исследовании о поведении ТАГ ABC при элюировании в хиральной хроматографии, ценны для изучения ТАГ в природных жирах и маслах. Однако для тщательного анализа энантиомеров ТАГ в сложных природных жирах и маслах, таких как жир грудного молока человека, необходимо предварительное разделение, чтобы уменьшить влияние изобарических ТАГ; поэтому потребуется 2D ЖХ разделение [40].

Связанное содержание

Дополнительная информация: Список синтезированных энантиомерно чистых эталонных соединений ТАГ, список коммерческих рацемических стандартов, хроматограммы 33 пар энантиомерно чистых ТАГ, проанализированных в данном исследовании, и часть хроматограмм изомеров ТАГ, иллюстрирующая разделение региоизомерных триплетов.

