= Комбинаторика
:eqnums:
:page-authors: ["Казаков Г.В.", "Сидоров Р.А."]
:page-doi: DRAFT
:page-excerpt: Формулы комбинаторики, используемые в моделях расчета триглицеринов.
:page-liquid:

:details: Детали
:examples: Примеры
:where: Где

// https://neerc.ifmo.ru/wiki/index.php?title=%D0%9A%D0%BE%D0%BC%D0%B1%D0%B8%D0%BD%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D1%8B%D0%B5_%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D1%8B

*{% for author in page.authors %}{{ author }}{% if forloop.last != true %}, {% endif %}{% endfor %}*

== Размещение

Размещение (англ. arrangement) -- из stem:[n] по stem:[k] -- упорядоченный набор stem:[k] различных элементов stem:[n]-элементного множества.

.{details}
[%collapsible]
====
Размещение -- это позиционно-зависимое расположение.

Пример: имеется stem:[k] человек и stem:[n] мест. Сколько существует способов разместить людей по местам?
====

[stem]
++++
\begin{equation}
    A_n^k = \frac{n!}{(n-k)!}
\end{equation}
++++
.{details}
[%collapsible]
=====
У нас есть stem:[k] предметов и stem:[n] свободных мест. Тогда разместить первый предмет мы сможем stem:[n] способами, второй: stem:[n-1], третий: stem:[n-2], ... stem:[k]-й: stem:[n-k+1]. Получаем stem:[N = n(n-1)(n-2)\cdot...\cdot(n-k+1)]; для удобства эту формулу представляют в виде stem:[\frac{n!}{(n-k)!}].
=====

== Размещение с повторениями

Размещение с повторениями (англ. arrangement with repetitions), из stem:[n] элементов по stem:[k] -- отображение множества stem:[k] первых натуральных чисел stem:[1,2,...,k] в данное множество stem:[{a_1,a_2,...,a_n}].

.{details}
[%collapsible]
====
Пример: имеется n книг, каждая в k экземплярах. Сколькими способами может быть сделан выбор книг из числа данных?
====

.Число размещений с повторениями из stem:[n] по stem:[k]
[stem]
++++
\begin{equation}
    \bar{A}_n^k = nk
\end{equation}
++++

== Сочетание

.Число сочетаний (позиционно-независимое расположение) из stem:[n] по stem:[k]
[stem]
++++
\begin{equation}
    C_n^k = \frac{n!}{(n-k)!k!}
\end{equation}
++++
.{details}
[%collapsible]
=====
Отличие размещения от сочетания в том, что элементы сочетания позиционно-независимы т.е., если мы поменяем любые из элементов местами, это будет тот же способ, что и прежде. Количество способов перестановки stem:[k] элементов между собой равно stem:[k!], отсюда и получаем формулу stem:[\frac{n!}{(n-k)!k!}]
=====

== Перестановка

Перестановка (англ. permutation) -- упорядоченный набор чисел stem:[1,2,\dots,n], представляющий собой биекцию на множестве stem:[\{1,2,\dots,n\}], которая числу stem:[i] ставит в соответствие stem:[i]-й элемент из набора.

.{details}
[%collapsible]
====
Пример: имеется stem:[n] книг. Сколько существует способов переставить книги на полке?
====

[stem]
++++
\begin{equation}
    P_n = n!
\end{equation}
++++

== Перестановка с повторениями

Перестановка с повторениями (англ. permutation with repetitions) -- те же перестановки, но некоторые элементы могут встречаться несколько раз.

.{details}
[%collapsible]
====
Пример: имеется набор книг stem:[{a_1,a_2,...,a_n}], каждая из которых имеется в stem:[k_1,k_2,...,k_n] экземплярах соответственно. Сколько существует способов переставить книги на полке?
====

[stem]
++++
\begin{equation}
    \bar{P}_n = \frac{(k_1+k_2+...+k_n)!}{k_1!k_2!...k_n!}
\end{equation}
++++
.{details}
[%collapsible]
====
[stem]
++++
\begin{align}
    &P_{[ABC]} &&=&& (1+1+1)! = 6 && [ABC], [ACB], [BAC], [BCA], [CAB], [CBA]\\
    &P_{[AAB]} &&=&& \frac{(2+1)!}{2!1!} = 3 && [AAB], [ABA], [BAA]\\
    &P_{[AAA]} &&=&& \frac{3!}{3!} = 1 && [AAA]\\
\end{align}
++++
====

'''

После 66% остался $S_2U$ $=>$ остался $[SSU]$, $[USS]$ или $[SUS]$.

- для типового состава (соответствует разложению бинома):
- $[S_2U] = [SSU] + [USS] + [SUS] = 3 * [S]^2 * [U]$
- $[SU_2] = [SUU] + [UUS] + [USU] = 3 * [S] * [U]^2$
- остальные значения не отличаются от значений стерео-типового и
позиционно-типового составов:
- $[S_3] = [S]^3$
- $[U_3] = [U]^3$

== Calculation

> stem:[3[A\] = 2[A\]_{13} + [A\]_2]{0248e842}

== Триглицерины (Triglycerides)

[stem]
++++
\begin{equation}
    \mathbb{A} = \{ a_1, a_2, \dots, a_n \}
\end{equation}
++++
.{where}
[%collapsible]
====
* stem:[\mathbb{A}] -- множество, представляющее виды stem:[FA];
* stem:[n] -- количество элементов множества stem:[\mathbb{A}];
* stem:[a_i] -- i-й элемент множества stem:[\mathbb{A}].
====

[stem]
++++
\begin{equation}
    \mathbb{S} = \{ s_1, s_2, \dots, s_{n_\mathbb{S}} \}
\end{equation}
++++
.{where}
[%collapsible]
====
* stem:[\mathbb{S}] -- подмножество множества stem:[\mathbb{A}], представляющее только насыщенные stem:[FA];
* stem:[n_\mathbb{S}] -- количество элементов множества stem:[\mathbb{S}].
====

[stem]
++++
\begin{equation}
    \mathbb{U} = \{ u_1, u_2, \dots, u_{n_\mathbb{U}} \}
\end{equation}
++++
.{where}
[%collapsible]
====
* stem:[\mathbb{U}] -- подмножество множества stem:[\mathbb{A}], представляющее только ненасыщенные stem:[FA];
* stem:[n_\mathbb{U}] -- количество элементов множества stem:[\mathbb{U}].
====

[stem]
++++
\begin{equation}
    \mathbb{T} = \{ S, U \}
\end{equation}
++++
.{where}
[%collapsible]
====
* stem:[\mathbb{T}] -- множество из двух элементов, представляющее типы элементов множества stem:[\mathbb{A}].
====

Трехэлементное размещение stem:[\{ a_{1}, a_{2}, a_{3} \}]
