= {page-title}
:eqnums:
:nofooter:
:showtitle:
:stem: latexmath
:page-authors: ["Казаков Г.В.", "Сидоров Р.А."]
:page-doi: DRAFT
:page-liquid:
:page-title: Теория Ганстоуна (Gunstone)
:details: Детали
:where: Где

:2fd49011: footnote:2fd49011-2923-59ed-ac33-2d84d8a2f33f[Верещагин А. Г. Биохимия триглицеридов. – 1972.]
:0248e842: footnote:0248e842-25d5-5a0d-b508-6c22c52890f5[Верещагин А. Г. Биохимия триглицеридов. – 1972, с. 116.]
:421c31cc: footnote:421c31cc-685c-52ef-8647-94a1dda24850[Верещагин А. Г. Биохимия триглицеридов. – 1972, с. 172.]
:56d7ba11: footnote:56d7ba11-82ca-5e72-a445-ff874bb5a5fd[Верещагин А. Г. Биохимия триглицеридов. – 1972, с. 174.]
:653b0659: footnote:653b0659-c81f-50d7-a344-7220f9840ae6[Верещагин А. Г. Биохимия триглицеридов. – 1972, с. 171.]
:10_1007__BF02632456: footnote:10_1007__BF02632456[Gunstone F. D. et al. Glyceride studies. V. The distribution of unsaturated acyl groups in vegetable triglycerides //Journal of the American Oil Chemists' Society. – 1965. – Т. 42. – №. 11. – С. 965-970. https://doi.org/10.1007/BF02632456[🔗]]

*{% for author in page.authors -%}{{ author }}{% if forloop.last != true %}, {% endif %}{% endfor %}*

Это 1,3 статистическое, 2 статистическое распределение.

Теория Ганстоуна описывает типовой и видовой составы исключительно растительных триглицеридов.

Позиционная специфичность распределения триглицеридов растений:

> кислоты первой категории (stem:[A_I]), включающие большинство ненасыщенных кислот, а также ненасыщенные кислоты с stem:[m > 18] сосредоточены почти полностью в 1,3-положениях, а 2-положения даже при stem:[[U\] = 37-38\%] на 95-100% заняты ненасыщенными кислотами с stem:[m \leq 18], образующими вторую категорию (stem:[A_{II}]){653b0659}

[#421c31cc]
> Теория Ганстоуна базируется на умозрительной гипотезе Савари и Денюэлля о двух позиционно-специфичных ферментах биосинтеза, согласно которой вначале в 2-положении статистически распределяются $A_{II}$, а затем 1,3-положения статистически замещаются смесью $A_I$ и остатка кислот $A_{II}$ (если он есть). {421c31cc}

'''

.Типовой состав по теории Ганстоуна
[stem]
++++
\begin{align}
    &[S_3]_{TC/G}  &&=&& \begin{cases}
        0\% < [S] < 66\%:   & 0\\
        66\% < [S] < 100\%: & 3[S] - 2 \equiv -3[U] + 1
    \end{cases}\\
    &[S_2U]_{TC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & (\frac32[S])^2 \equiv \frac32([S] - [S][U]) \equiv (\frac32 - \frac32[U])^2\\
        66\% < [S] < 100\%: & -3[S] + 3 \equiv 3[U]
    \end{cases}\\
    &[SU_2]_{TC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & -\frac92[S]^2 + 3[S] \equiv \frac32[S](3[U] - 1) \equiv -\frac92[U]^2 + 6[U] - \frac32\\
        66\% < [S] < 100\%: & 0
    \end{cases}\\
    &[U_3]_{TC/G}  &&=&& \begin{cases}
        0\% < [S] < 66\%:   & (1 - \frac32[S])^2 \equiv (\frac32[U] - \frac12)^2\\
        66\% < [S] < 100\%: & 0
    \end{cases}
\end{align}
++++

.{details}
[%collapsible]
====
[stem]
++++
\begin{align}
    &[S] = 1 - [U]\\
    &p = \frac32[S] = \frac32 - \frac32[U]\\
    &q = 1 - p = 1 - \frac32[S] = \frac32[U] - \frac12\\
    \begin{cases}
        0\% < [S] < 66\%:   & \begin{cases}
            f([U_3]) \equiv f([U'_2]) = q^2\\
            f([SU_2]) \equiv f([S'U']) = 2pq\\
            f([S_2U]) \equiv f([S'_2]) = p^2
        \end{cases}\\
        66\% < [S] < 100\%: & \begin{cases}
            f([S_2U]) \equiv f([U']) = -3[S] + 3 \equiv 3[U]\\
            f([S_3]) \equiv f([S']) = 3[S] - 2 \equiv - 3[U] + 1
        \end{cases}
    \end{cases}
\end{align}
++++
====

.Видовой состав по теории Ганстоуна
[stem]
++++
\begin{align}
    &[^1S^2S^3S]_{SC/G} &&=&& 6 \frac{[^1S][^2S][^3S]}{[S]^3} [S_3]_{TC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & 0\\
        66\% < [S] < 100\%: & 6 \frac{[^1S][^2S][^3S]}{[S]^3} (3[S] - 2)
    \end{cases}\\
    &[^1S^2S_2]_{SC/G}  &&=&& 3 \frac{[^1S][^2S]^2}{[S]^3} [S_3]_{TC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & 0\\
        66\% < [S] < 100\%: & 3 \frac{[^1S][^2S]^2}{[S]^3} (3[S] - 2)
    \end{cases}\\
    &[^1S_3]_{SC/G}     &&=&& \frac{[^1S]^3}{[S]^3} [S_3]_{TC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & 0\\
        66\% < [S] < 100\%: & \frac{[^1S]^3}{[S]^3} (3[S] - 2)
    \end{cases}\\

    &[^1S^1U^2S]_{SC/G} &&=&& 2 \frac{[^1S][^1U][^2S]}{[S]^2[U]} [S_2U]_{TC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & \frac92 \frac{[^1S][^1U][^2S]}{[U]}\\
        66\% < [S] < 100\%: & 6 \frac{[^1S][^1U][^2S]}{[S]^2}
    \end{cases}\\
    &[^1S^1U^1S]_{SC/G} &&=&& \frac{[^1S]^2[^1U]}{[S]^2[U]} [S_2U]_{TC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & \frac94 \frac{[^1S]^2[^1U]}{[U]}\\
        66\% < [S] < 100\%: & 3 \frac{[^1S]^2[^1U]}{[S]^2}
    \end{cases}\\

    &[^1S^1U^2U]_{SC/G} &&=&& 4 \frac{[^1U][^2U][^3U]}{[U]^3} [SU_2]_{TC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & 6 \frac{[^1U][^2U][^3U]}{[U]^2} (3[U] - 1)\\
        66\% < [S] < 100\%: & 0
    \end{cases}\\
    &[^1S^1U^1U]_{SC/G} &&=&& 2 \frac{[^1U][^2U]^2}{[U]^2} [SU_2]_{TC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & 3 \frac{[^1U][^2U]^2}{[U]^2} (3[U] - 1)\\
        66\% < [S] < 100\%: & 0
    \end{cases}\\

    &[^1U^2U^3U]_{SC/G} &&=&& 6 \frac{[^1U][^2U][^3U]}{[U]^3} [U_3]_{TC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & 6 \frac{[^1U][^2U][^3U]}{[U]^3} (\frac32[U] - \frac12)^2\\
        66\% < [S] < 100\%: & 0
    \end{cases}\\
    &[^1U^2U_2]_{SC/G}  &&=&& 3 \frac{[^1U][^2U]^2}{[U]^3} [U_3]_{TC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & 3 \frac{[^1U][^2U]^2}{[U]^3} (\frac32[U] - \frac12)^2\\
        66\% < [S] < 100\%: & 0
    \end{cases}\\
    &[^1U_3]_{SC/G}     &&=&& \frac{[^1U]^3}{[U]^3} [U_3]_{TC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & \frac{[^1U]^3}{[U]^3} (\frac32[U] - \frac12)^2\\
        66\% < [S] < 100\%: & 0
    \end{cases}
\end{align}
++++

.{details}
[%collapsible]
====
[stem]
++++
\begin{align}
    &P_{[^1A^2A^3A]} = [^1A^2A^3A], [^1A^3A^2A], [^2A^1A^3A], [^2A^3A^1A], [^3A^1A^2A], [^3A^2A^1A] &(\times6)\\
    &P_{[^1A^2A^2A]} = [^1A^2A^2A], [^2A^1A^2A], [^2A^2A^1A] &(\times3)\\
    &P_{[^1A^1A^1A]} = [^1A^1A^1A] &(\times1)\\

    &P_{[^1S^1U^2S]} = [^1S^1U^2S], [^2S^1U^1S] &(\times2)\\
    &P_{[^1S^1U^1S]} = [^1S^1U^1S] &(\times1)\\

    &P_{[^1S^1U^2U]} = [^1S^1U^2U], [^1S^2U^1U], [^1U^2U^1S], [^2U^1U^1S] &(\times4)\\
    &P_{[^1S^1U^1U]} = [^1S^1U^1U], [^1U^1U^1S] &(\times2)\\
\end{align}
++++
====

> Вычисление ПТС исключается, поскольку при stem:[[S\] < 66\%] stem:[[S_2U\]_G = [SUS\]], а stem:[[SU_2\]_G = [SUU\]].{56d7ba11}

Воспользуемся результатами расчета ТС по теории Ганстоуна, абстрагировавшись от xref:421c31cc[изначальной гипотезы] и предположив, что виды внутри типа распределяются прямо пропорционально факторам селективности{101007BF02632456}{101007s11746-014-2553-8} их составляющих. В результате получим значения ПВС и СВС, близкие к рассчитанным по Вандер Валю.

.Позиционно-видовой состав по модифицированной теории Ганстоуна
[stem]
++++
\begin{align}
    &[SSS]_{PSC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & 0\\
        66\% < [S] < 100\%: & \frac{[^1S_F][^2S_F][^3S_F]}{[S]^3} (3[S] - 2)
    \end{cases}\\
    &[SSU]_{PSC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & \frac32 \frac{[^1S_F][^2S_F][^3U_F]}{[U]}\\
        66\% < [S] < 100\%: & 2 \frac{[^1S_F][^2S_F][^3U_F]}{[S]^2}
    \end{cases}\\
    &[SUS]_{PSC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & \frac34 \frac{[^1S_F][^2U_F][^3S_F]}{[U]}\\
        66\% < [S] < 100\%: & \frac{[^1S_F][^2U_F][^3S_F]}{[S]^2}
    \end{cases}\\
    &[SUU]_{PSC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & \frac{[^1S_F][^2U_F][^3U_F]}{[U]^2} (3[U] - 1)\\
        66\% < [S] < 100\%: & 0
    \end{cases}\\
    &[USU]_{PSC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & \frac12 \frac{[^1U_F][^2S_F][^3U_F]}{[U]^2} (3[U] - 1)\\
        66\% < [S] < 100\%: & 0
    \end{cases}\\
    &[UUU]_{PSC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & \frac14 \frac{[^1U_F][^2U_F][^3U_F]}{[S]^3}{[S]^3} (3[U] - 1)^2\\
        66\% < [S] < 100\%: & 0
    \end{cases}
\end{align}
++++

.{details}
[%collapsible]
====
[stem]
++++
\begin{align}
    [^nA_F] = [^nA]_{123}F_{[^nA]_n}\\
\end{align}
++++

[stem]
++++
\begin{align}
    &[SSS]_{PSC/G} &&=&& \frac{[^1S_F][^2S_F][^3S_F]}{[S]^3} [S_3]_{TC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & 0\\
        66\% < [S] < 100\%: & \frac{[^1S_F][^2S_F][^3S_F]}{[S]^3} (3[S] - 2)
    \end{cases}\\
    &[SSU]_{PSC/G} &&=&& \frac23 \frac{[^1S_F][^2S_F][^3U_F]}{[S]^2[U]} [S_2U]_{TC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & \frac23 \frac{[^1S_F][^2S_F][^3U_F]}{[S]^2[U]} (\frac32[S])^2\\
        66\% < [S] < 100\%: & \frac23 \frac{[^1S_F][^2S_F][^3U_F]}{[S]^2[U]} 3[U]
    \end{cases}\\
    &[SUS]_{PSC/G} &&=&& \frac13 \frac{[^1S_F][^2U_F][^3S_F]}{[S]^2[U]} [S_2U]_{TC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & \frac13 \frac{[^1S_F][^2U_F][^3S_F]}{[S]^2[U]} (\frac32[S])^2\\
        66\% < [S] < 100\%: & \frac13 \frac{[^1S_F][^2U_F][^3S_F]}{[S]^2[U]} 3[U]
    \end{cases}\\
    &[SUU]_{PSC/G} &&=&& \frac23 \frac{[^1S_F][^2U_F][^3U_F]}{[S][U]^2} [SU_2]_{TC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & \frac23 \frac{[^1S_F][^2U_F][^3U_F]}{[S][U]^2} \frac32[S](3[U] - 1)\\
        66\% < [S] < 100\%: & 0
    \end{cases}\\
    &[USU]_{PSC/G} &&=&& \frac13 \frac{[^1U_F][^2S_F][^3U_F]}{[S][U]^2} [SU_2]_{TC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & \frac13 \frac{[^1U_F][^2S_F][^3U_F]}{[S][U]^2} \frac32[S](3[U] - 1)\\
        66\% < [S] < 100\%: & 0
    \end{cases}\\
    &[UUU]_{PSC/G} &&=&& \frac{[^1U_F][^2U_F][^3U_F]}{[S]^3} [U_3]_{TC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & \frac{[^1U_F][^2U_F][^3U_F]}{[S]^3} (\frac32[U] - \frac12)^2\\
        66\% < [S] < 100\%: & 0
    \end{cases}
\end{align}
++++
====

.Позиционно-типовой состав по теории Ганстоуна
[stem]
++++
\begin{cases}
    &[SSS]_{PTC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & 0\\
        66\% < [S] < 100\%: & 3[S] - 2
    \end{cases}\\
    &[SSU]_{PTC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & (\frac23[S])^2\\
        66\% < [S] < 100\%: & 2[U]
    \end{cases}\\
    &[SUS]_{PTC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & (\frac16[S])^2\\
        66\% < [S] < 100\%: & [U]
    \end{cases}\\
    &[SUU]_{PTC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & [S](3[U] - 1)\\
        66\% < [S] < 100\%: & 0
    \end{cases}\\
    &[USU]_{PTC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & \frac12[S](3[U] - 1)\\
        66\% < [S] < 100\%: & 0
    \end{cases}\\
    &[UUU]_{PTC/G} &&=&& \begin{cases}
        0\% < [S] < 66\%:   & (\frac32[U] - \frac12)^2\\
        66\% < [S] < 100\%: & 0
    \end{cases}
\end{cases}
++++

'''

.Позиционно-типовой состав
[stem]
++++
\begin{align}
    &[SSS]_{PTC} &&=&& [S_3]_{TC}\\
    &[SSU]_{PTC} &&=&& \frac23[S_2U]_{TC}\\
    &[SUS]_{PTC} &&=&& \frac13[S_2U]_{TC}\\
    &[SUU]_{PTC} &&=&& \frac23[SU_2]_{TC}\\
    &[USU]_{PTC} &&=&& \frac13[SU_2]_{TC}\\
    &[UUU]_{PTC} &&=&& [U_3]_{TC}\\
\end{align}
++++

.Стерео-типовой состав
[stem]
++++
\begin{align}
    &[SSS]_{STC} &&=&& [SSS]_{PTC}        &&=&& [S_3]_{TC}\\
    &[SSU]_{STC} &&=&& \frac12[SSU]_{PTC} &&=&& \frac13[S_2U]_{TC}\\
    &[USS]_{STC} &&=&& \frac12[SSU]_{PTC} &&=&& \frac13[S_2U]_{TC}\\
    &[SUS]_{STC} &&=&& [SUS]_{PTC}        &&=&& \frac13[S_2U]_{TC}\\
    &[SUU]_{STC} &&=&& \frac12[SUU]_{PTC} &&=&& \frac13[SU_2]_{TC}\\
    &[UUS]_{STC} &&=&& \frac12[SUU]_{PTC} &&=&& \frac13[SU_2]_{TC}\\
    &[USU]_{STC} &&=&& [USU]_{PTC}        &&=&& \frac13[SU_2]_{TC}\\
    &[UUU]_{STC} &&=&& [UUU]_{PTC}        &&=&& [U_3]_{TC}\\
\end{align}
++++

.Видовой состав
[stem]
++++
\begin{align}
    &[^1S^2S^3S]_{SC} &&=&& 6 \frac{[^1S]}{[S]} \frac{[^2S]}{[S]} \frac{[^3S]}{[S]} [S_3]_{TC}\\
    &[^1S^2S_2]_{SC}  &&=&& 3 \frac{[^1S][^2S]^2}{[S]^3} [S_3]_{TC}\\
    &[^1S_3]_{SC}     &&=&& \frac{[^1S]^3}{[S]^3} [S_3]_{TC}\\

    &[^1S^2S^1U]_{SC} &&=&& 6 \frac{[^1S][^2S][^1U]}{[S]^2[U]} [S_2U]_{TC}\\
    &[^1S_2^1U]_{SC}  &&=&& 3 \frac{[^1S]^2[^1U]}{[S]^2[U]} [S_2U]_{TC}\\

    &[^1S^1U^2U]_{SC} &&=&& 6 \frac{[^1U][^2U][^3U]}{[U]^3} [SU_2]_{TC}\\
    &[^1S^1U_2]_{SC}  &&=&& 3 \frac{[^1U][^2U]^2}{[U]^2} [SU_2]_{TC}\\

    &[^1U^2U^3U]_{SC} &&=&& 6 \frac{[^1U][^2U][^3U]}{[U]^3} [U_3]_{TC}\\
    &[^1U^2U_2]_{SC}  &&=&& 3 \frac{[^1U][^2U]^2}{[U]^3} [U_3]_{TC}\\
    &[^1U_3]_{SC}     &&=&& \frac{[^1U]^3}{[U]^3} [U_3]_{TC}\\
\end{align}
++++

.{details}
[%collapsible]
====
[stem]
++++
\begin{align}
    &P_{[ABC]} &&=&& [ABC], [ACB], [BAC], [BCA], [CAB], [CBA] &(\times6)\\
    &P_{[A_2B]} &&=&& [AAB], [ABA], [BAA] &(\times3)\\
    &P_{[A_3]} &&=&& [AAA] &(\times1)\\
\end{align}
++++
====

.{details}
[%collapsible]
====

.Множество, представляющее виды stem:[FA].
stem:[n] - количество элементов множества stem:[A].
[stem]
++++
\begin{equation}
    A = \{ a_1, a_2, \dots, a_n \}
\end{equation}
++++
.{where}
[%collapsible]
=====
* stem:[a] -- левый верхний элемент матрицы;
* stem:[b] -- правый верхний элемент матрицы;
=====

* stem:[S = \{ s_1, s_2, \dots, s_{n_S} \}]
+
Подмножество stem:[A], представляющее только насыщенные stem:[FA]. +
stem:[n_S] - количество элементов множества stem:[S].
* stem:[U = \{ u_1, u_2, \dots, u_{n_U} \}]
+
Подмножество множества stem:[A], представляющее только ненасыщенные stem:[FA]. +
stem:[n_U] - количество элементов множества stem:[U].
* Множество stem:[T]: stem:[T = \{ s, u \}]
+
Это множество из двух элементов, представляющее типы элементов множества stem:[A].

Трехэлементное размещение stem:[\{ a_{1}, a_{2}, a_{3} \}]

.Число размещений с повторениями из stem:[n] по stem:[k]
[stem]
++++
\begin{equation}
    \bar{A}_n^k = nk
\end{equation}
++++

.Число размещений (позиционно-зависимое расположение) из stem:[n] по stem:[k]
[stem]
++++
\begin{equation}
    A_n^k = \frac{n!}{(n-k)!}
\end{equation}
++++

.{details}
[%collapsible]
=====
У нас есть stem:[k] предметов и stem:[n] свободных мест. Тогда разместить первый предмет мы сможем stem:[n] способами, второй: stem:[n-1], третий: stem:[n-2], ... stem:[k]-й: stem:[n-k+1]. Получаем stem:[N = n(n-1)(n-2)\cdot...\cdot(n-k+1)]; для удобства эту формулу представляют в виде stem:[\frac{n!}{(n-k)!}].
=====

.Число сочетаний (позиционно-независимое расположение) из stem:[n] по stem:[k]:
[stem]
++++
\begin{equation}
    C_n^k = \frac{n!}{(n-k)!k!}
\end{equation}
++++

.{details}
[%collapsible]
=====
Отличие размещения от сочетания в том, что элементы сочетания позиционно-независимы т.е., если мы поменяем любые из элементов местами, это будет тот же способ, что и прежде. Количество способов перестановки stem:[k] элементов между собой равно stem:[k!], отсюда и получаем формулу stem:[\frac{n!}{(n-k)!k!}]
=====

.Число перестановок из stem:[n]:
[stem]
++++
\begin{equation}
    P_n = n!
\end{equation}
++++
====

'''

[stem]
++++
\begin{cases}
    0\% < [S] < 66\% & 1 - ([SU_2] + [S_2U]) = 1 - 3 * ([S]^2 * [U] + [S] * [U]^2) = ((3 * [U] - 1) / 20)^2\\
    66\% < [S] < 100\% & 0
\end{cases}$
++++

После 66% остался $S_2U$ $=>$ остался $[SSU]$, $[USS]$ или $[SUS]$.

- для типового состава (соответствует разложению бинома):
    - $[S_2U] = [SSU] + [USS] + [SUS] = 3 * [S]^2 * [U]$
    - $[SU_2] = [SUU] + [UUS] + [USU] = 3 * [S] * [U]^2$
    - остальные значения не отличаются от значений стерео-типового и
        позиционно-типового составов:
        - $[S_3] = [S]^3$
        - $[U_3] = [U]^3$

== Calculation

> stem:[3[A\] = 2[A\]_{13} + [A\]_2]{0248e842}
