= {page-title}
:eqnums:
:nofooter:
:showtitle:
:stem: latexmath
:page-authors: ["Казаков Г.В.", "Сидоров Р.А."]
:page-doi: DRAFT
:page-excerpt: Excerpt goes here.
:page-liquid:
:page-title: Модифицированная теория Ганстоуна (Gunstone)
:details: Детали

:2fd49011: footnote:2fd49011-2923-59ed-ac33-2d84d8a2f33f[Верещагин А. Г. Биохимия триглицеридов. – 1972.]
:0248e842: footnote:0248e842-25d5-5a0d-b508-6c22c52890f5[Верещагин А. Г. Биохимия триглицеридов. – 1972, с. 116.]
:421c31cc: footnote:421c31cc-685c-52ef-8647-94a1dda24850[Верещагин А. Г. Биохимия триглицеридов. – 1972, с. 172.]
:56d7ba11: footnote:56d7ba11-82ca-5e72-a445-ff874bb5a5fd[Верещагин А. Г. Биохимия триглицеридов. – 1972, с. 174.]
:653b0659: footnote:653b0659-c81f-50d7-a344-7220f9840ae6[Верещагин А. Г. Биохимия триглицеридов. – 1972, с. 171.]

:101007BF02632456: footnote:101007BF02632456[Gunstone F. D. et al. Glyceride studies. V. The distribution of unsaturated acyl groups in vegetable triglycerides //Journal of the American Oil Chemists' Society. – 1965. – Т. 42. – №. 11. – С. 965-970. https://doi.org/10.1007/BF02632456[🔗^]]
:101007s11746-014-2553-8: footnote:101007s11746-014-2553-8[Sidorov R. A. et al. Positional‐Species Composition of Triacylglycerols from the Arils of Mature Euonymus Fruits //Journal of the American Oil Chemists' Society. – 2014. – Т. 91. – №. 12. – С. 2053-2063. https://doi.org/10.1007/s11746-014-2553-8[🔗^]]

Это 1,3 статистическое, 2 статистическое распределение.

Описывает типовой и видовой составы исключительно растительных триглицеридов.

Позиционная специфичность распределения триглицеридов растений:

> кислоты первой категории (stem:[A_I]), включающие большинство ненасыщенных кислот, а также ненасыщенные кислоты с stem:[m > 18] сосредоточены почти полностью в 1,3-положениях, а 2-положения даже при stem:[[U\] = 37-38\%] на 95-100% заняты ненасыщенными кислотами с stem:[m \leq 18], образующими вторую категорию (stem:[A_{II}]){653b0659}

[#421c31cc]
> Теория Ганстоуна базируется на умозрительной гипотезе Савари и Денюэлля о двух позиционно-специфичных ферментах биосинтеза, согласно которой вначале в 2-положении статистически распределяются stem:[A_{II}], а затем 1,3-положения статистически замещаются смесью stem:[A_I] и остатка кислот stem:[A_{II}] (если он есть).{421c31cc}

'''

.Типовой состав по теории Ганстоуна
[stem]
++++
\begin{align}
  &[S_3]  &&=&& \begin{cases}
    0\% < [S] < 66\%:   & 0\\
    66\% < [S] < 100\%: & 3[S] - 2 \equiv -3[U] + 1
  \end{cases}\\
  &[S_2U] &&=&& \begin{cases}
    0\% < [S] < 66\%:   & (\frac32[S])^2 \equiv \frac32([S] - [S][U]) \equiv (\frac32 - \frac32[U])^2\\
    66\% < [S] < 100\%: & -3[S] + 3 \equiv 3[U]
  \end{cases}\\
  &[SU_2] &&=&& \begin{cases}
    0\% < [S] < 66\%:   & -\frac92[S]^2 + 3[S] \equiv \frac32[S](3[U] - 1) \equiv -\frac92[U]^2 + 6[U] - \frac32\\
    66\% < [S] < 100\%: & 0
  \end{cases}\\
  &[U_3]  &&=&& \begin{cases}
    0\% < [S] < 66\%:   & (1 - \frac32[S])^2 \equiv (\frac32[U] - \frac12)^2\\
    66\% < [S] < 100\%: & 0
  \end{cases}
\end{align}
++++

.Типовой состав по теории Ганстоуна при 0% < [S] < 66%
[stem]
++++
\begin{align}
  &[S_3]  &&=&& 0\\
  &[S_2U] &&=&& (\frac32[S])^2 \equiv \frac32([S] - [S][U]) \equiv (\frac32 - \frac32[U])^2\\
  &[SU_2] &&=&& -\frac92[S]^2 + 3[S] \equiv \frac32[S](3[U] - 1) \equiv -\frac92[U]^2 + 6[U] - \frac32\\
  &[U_3]  &&=&& (1 - \frac32[S])^2 \equiv (\frac32[U] - \frac12)^2\\
\end{align}
++++

> Вычисление ПТС исключается, поскольку при stem:[[S\] < 66\%] stem:[[S_2U\]_G = [SUS\]], а stem:[[SU_2\]_G = [SUU\]].{56d7ba11}

Воспользуемся результатами расчета ТС по теории Ганстоуна, абстрагировавшись от xref:421c31cc[изначальной гипотезы] и предположив, что виды внутри типа распределяются прямо пропорционально факторам селективности{101007BF02632456}{101007s11746-014-2553-8} их составляющих. В результате получим значения ПВС и СВС, близкие к рассчитанным по Вандер Валю.

.Позиционно-видовой состав по модифицированной теории Ганстоуна
[stem]
++++
\begin{align}
  &[SSS] &&=&& \begin{cases}
    0\% < [S] < 66\%:   & 0\\
    66\% < [S] < 100\%: & \frac{[^1S_F] \times [^2S_F] \times [^3S_F]}{[S]^3} \times (3[S] - 2)
  \end{cases}\\
  &[SSU] &&=&& \begin{cases}
    0\% < [S] < 66\%:   & \frac32 \times \frac{[^1S_F] \times [^2S_F] \times [^3U_F]}{[U]}\\
    66\% < [S] < 100\%: & 2 \times \frac{[^1S_F] \times [^2S_F] \times [^3U_F]}{[S]^2}
  \end{cases}\\
  &[SUS] &&=&& \begin{cases}
    0\% < [S] < 66\%:   & \frac34 \times \frac{[^1S_F] \times [^2U_F] \times [^3S_F]}{[U]}\\
    66\% < [S] < 100\%: & \frac{[^1S_F] \times [^2U_F] \times [^3S_F]}{[S]^2}
  \end{cases}\\
  &[SUU] &&=&& \begin{cases}
    0\% < [S] < 66\%:   & \frac{[^1S_F] \times [^2U_F] \times [^3U_F]}{[U]^2} \times (3[U] - 1)\\
    66\% < [S] < 100\%: & 0
  \end{cases}\\
  &[USU] &&=&& \begin{cases}
    0\% < [S] < 66\%:   & \frac12 \times \frac{[^1U_F] \times [^2S_F] \times [^3U_F]}{[U]^2} \times (3[U] - 1)\\
    66\% < [S] < 100\%: & 0
  \end{cases}\\
  &[UUU] &&=&& \begin{cases}
    0\% < [S] < 66\%:   & \frac14 \times \frac{[^1U_F] \times [^2U_F] \times [^3U_F]}{[S]^3} \times (3[U] - 1)^2\\
    66\% < [S] < 100\%: & 0
  \end{cases}
\end{align}
++++

.Позиционно-видовой состав по модифицированной теории Ганстоуна при 0% < [S] < 66%:
[stem]
++++
\begin{align}
  &[SSS] &&=&& 0\\
  &[SSU] &&=&& \frac32 \times \frac{[^1S_F] \times [^2S_F] \times [^3U_F]}{[U]}\\
  &[SUS] &&=&& \frac34 \times \frac{[^1S_F] \times [^2U_F] \times [^3S_F]}{[U]}\\
  &[SUU] &&=&& \frac{[^1S_F] \times [^2U_F] \times [^3U_F]}{[U]^2} \times (3[U] - 1)\\
  &[USU] &&=&& \frac12 \times \frac{[^1U_F] \times [^2S_F] \times [^3U_F]}{[U]^2} \times (3[U] - 1)\\
  &[UUU] &&=&& \frac14 \times \frac{[^1U_F] \times [^2U_F] \times [^3U_F]}{[S]^3} \times (3[U] - 1)^2\\
\end{align}
++++

.{details}
[%collapsible]
====
[stem]
++++
\begin{align}
  [^nS_F] = [^nS]_{1,2,3} \times F_{[^nS]_n}\\
  [^nU_F] = [^nU]_{1,2,3} \times F_{[^nU]_n}
\end{align}
++++
====
