.PDF to MD
[source,text]
Из документа возьми главную таблицу и выведи ее в виде блока кода markdown.
Также добавь самым первым столбцом название вещества (первый столбец таблицы) в виде 18:3-9,12,15.
Также добавь после столбца "Время (мин)" относительное время - это "Время (мин)" текущего столбца, деленное на "Время (мин)" 17:0.

Пример выходных данных:
.Семена 0 мм [1] (100 uL 17:0)
| Обозначение| Компонент            | Время (мин)| Относительное время| Площадь (мВ*с)| Площадь (%)
| 14:0       | Methyl tetradecanoate| 0.000      | 0.000              | 0.000         | 0.000

.Merge MD
[source,text]
Напиши код на Python. Ниже таблицы с повторностям, разделенные пустой строкой. Если заголовки таблиц совпадают за исключением повторностей (заключены в квадратные скобки), то это повторности одного эксперимента.
Нужно объединить повторности экспериментов в массив значений через запятую: [9.111,9.115,9.112].
Вывести итоговую таблицу в виде таблицы markdown.

Пример выходных данных:
.Семена 0 мм (100 uL 17:0)
| Обозначение| Компонент            | Время (мин)           | Относительное время   | Площадь (мВ*с)                      | Площадь (%)
| 14:0       | Methyl tetradecanoate| [13.511,13.625,13.633]| [0.6924,0.6930,0.6930]| [913250.247,1256200.755,1381815.398]| [0.175,0.208,0.200]


.Merge MD
[source,text]
Напиши код на Python. Ниже таблицы с повторностям, разделенные пустой строкой. Если заголовки таблиц совпадают за исключением повторностей (заключены в квадратные скобки), то это повторности одного эксперимента. Нужно объединить повторности эксперимента в одну таблицу.
Одинаковые вещества должны иметь очень близкое "Относительное время"(4 столбец) - это самый точный кретерии идентичности веществ и очень близкое "Время (мин)"(3 столбец). Если "Время" 0 то в этой повторности не задетектировано такое вещество (фактическое время у данного вецества не нулевое), тогда сравнивай вещества по столбцам "Обозначение", "Компонент" и "Площадь".
Если по относительному времени вещество лучше совпадает с другим веществом в других повторностях, то эту повторность следует переставить. При этом можно также смотреть столбец "Площадь (%)" - у него тоже значения будут более соответствующими меняемым повторностям. Если есть переставляемые в другое вещество повторности - напиши о них после таблицы.
Cтолбцы "Компонент" могут быть не полностью одинаковыми, но должны быть очень похожи. Если есть сомнения - напиши об этом.
В объединенных столбцах записывай массив значений через запятую: [9.111,9.115,9.112]
Выведи итоговую таблицу в виде кода markdown.

Пример выходных данных:
.Семена 0 мм (100 uL 17:0)
| Обозначение| Компонент            | Время (мин)           | Относительное время   | Площадь (мВ*с)                      | Площадь (%)
| 14:0       | Methyl tetradecanoate| [13.511,13.625,13.633]| [0.6924,0.6930,0.6930]| [913250.247,1256200.755,1381815.398]| [0.175,0.208,0.200]

[source,text]
Напиши код на Python, SciPy, чтобы для таблицы, подобной ниже, в столбцах которой находится массив с повторностями.
Для столбцов "Время", "Относительное время" расчитывалось среднее арифметическое и стандартное отклонение (ddof=1). Если в какий-то из повторностей значение 0 - считай по оставшимся повторностям и пиши восклицательный знак в конце.
Для столбцов "Площадь (мВ*с)" и "Площадь (%)" расчитывалось среднее арифметическое и стандартное отклонение (ddof=1). Если в какой-то из повторностей значение 0 - считай с учетом этого нуля и пиши восклицательный знак в конце.
Выводилось среднее и стандартное отклонение в одном столбце в виде "9.1234 ±0.1234".
Выведилась итоговая таблица в виде кода markdown.

Напиши код на Python, SciPy, чтобы для таблицы, подобной ниже, в столбцах которой находится массив с повторностями.
Для столбцов "Масса, mg/g", расчитывалось среднее арифметическое и стандартное отклонение (ddof=1).
Выводилось среднее и стандартное отклонение в одном столбце в виде "9.1234 ±0.1234".
Выведилась итоговая таблица в виде кода markdown.

***
Для таблицы ниже напиши код на Python, SciPy, который проверяет долю сухого веса (DW/FW).
Расчитывает среднее арифметическое и стандартное отклонение (ddof=1) для столбцов "m_2" "m_4" (повторности заданы индексом в столбце ID)
Среднее и стандартное отклонение должны выводиться в одном столбце в виде "9.1234 ±0.1234".
Итоговая таблица должна выводиться в виде markdown.


Напиши код на Python, SciPy. Код должен парсить таблицы, подобные ниже. Cчитать сумму Площадей ("Площадь (мВ*с)") всех веществ, которые есть в таблице за исключением 17:0, делить её на площадь 17:0 и умножить на массу 17:0. Массу рассчитай: в 100 uL = 0.025 мг; бъем 17:0 указан в заголовке таблицы в скобках, например "(100 uL 17:0)".

Добавь возможность вводить несколько таблиц, разделенных новой строкой и считай для каждой отдельно
Масса 17:0 = 0.15 мг;
***

[source,text]
Ниже таблицы с тремя повторностям. Объедини их в одну таблицу.
Одинаковые вещества должны иметь очень близкое "Относительное время" - это самый точный кретерии идентичности веществ и очень близкое "Время (мин)". Если время 0, то сравнивай вещества по столбцам "Обозначение" и "Компонент".
Если по относительному времени вещество лучше совпадает с другим веществом в других повторностях, то эту повторность следует переставить. При этом можешь также смотреть столбец "Площадь (%)" - у него тоже значения будут более соответствующими меняемым повторностям. Такие переставляемые в другое вещество повторности - напиши о них после таблицы.
Cтолбцы "Компонент" могут быть не полностью одинаковыми, но должны быть очень похожи.
Если есть сомнения - напиши об этом до таблицы.
В объединенных столбцах записывай массив значений через запятую: [9.111,9.115,9.112]
Выведи итоговую таблицу и таблицу с перестановками в виде блока кода markdown.

[source,text]
Преобразуй таблицу из markdown в google sheets.

Обозначение	Компонент	Время 1	Время 2	Время 3	Время ср.	Отн. время 1	Отн. время 2	Отн. время 3	Отн. время ср.	Площадь 1	Площадь 2	Площадь 3	Площадь ср.	Площадь % 1	Площадь % 2	Площадь % 3	Площадь % ср.

Для таблиц посчитай сумму Площадей всех веществ, которые есть в таблице за исключением 17:0. Раздели на площадь 17:0. И умножь на массу 17:0;
Масса 17:0 = 0.15 мг;
Объем 17:0 = 500 uL; В 100 uL = 0.025mg;

Выведи в виде таблицы markdown

Тут по три повторности. Выведи среднее и стандартное отклонение по трем повторностям.

